<?php

namespace Ais\PrestasiBundle\Repository;

/**
 * PrestasiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestasiRepository extends \Doctrine\ORM\EntityRepository
{
}
